import type { CategoryId } from "./categories";

export type ToolLink = {
  title: string;
  href: string;
  category: CategoryId;
  description: string;
  tags: string[];
  featured?: boolean;
  monumentRelevant?: boolean;
  iconUrl?: string;
};

export const tools: ToolLink[] = [
  {
    title: "Monument Support Guide",
    href: "https://help.bungie.net/hc/en-us/articles/49848696022548-Destiny-2-Monument-of-Triumph-and-Update-9-7-0-Support-Guide",
    category: "official",
    description: "Monument of Triumph access, activities, and install notes.",
    tags: ["monument", "support", "update 9.7.0"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "Monument Is Live",
    href: "https://www.bungie.net/7/en/News/Article/monument_of_triumph_is_live",
    category: "official",
    description: "Overview of the Director, activities, gear, rewards, and systems.",
    tags: ["monument", "overview", "bungie"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "Update 9.7.0",
    href: "https://www.bungie.net/7/en/News/Article/destiny_update_9_7_0",
    category: "official",
    description: "Monument of Triumph patch notes: rewards, activities, and sandbox.",
    tags: ["patch notes", "sandbox", "rewards"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "Update 9.7.0.1",
    href: "https://www.bungie.net/7/en/News/Article/destiny_update_9_7_0_1",
    category: "official",
    description: "June 16, 2026 hotfix notes.",
    tags: ["hotfix", "pantheon", "dungeons"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "Known Issues",
    href: "https://help.bungie.net/hc/en-us/articles/39007140765204-Destiny-2-Known-Issues-and-Vital-Information",
    category: "official",
    description: "Known issues for Monument of Triumph and recent releases.",
    tags: ["known issues", "support", "bugs"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "Monument FAQ",
    href: "https://help.bungie.net/hc/en-us/articles/50100493304468--13-Monument-of-Triumph-FAQ",
    category: "official",
    description: "Returning-player answers for power, armor stats, vendors, and first steps.",
    tags: ["faq", "returning players", "armor"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "Destiny Item Manager",
    href: "https://destinyitemmanager.com/en/",
    category: "inventory",
    description: "Item moves, vault search, tags, and loadouts.",
    tags: ["inventory", "loadouts", "vault"],
    featured: true,
  },
  {
    title: "D2ArmorPicker",
    href: "https://d2armorpicker.com/",
    iconUrl: "https://d2armorpicker.com/favicon.ico",
    category: "inventory",
    description: "Armor combinations for target stats.",
    tags: ["armor", "stats", "optimizer"],
  },
  {
    title: "D2Checklist",
    href: "https://www.d2checklist.com/",
    category: "inventory",
    description: "Gear manager, roll flags, collections, and progress.",
    tags: ["checklist", "vault", "progress"],
  },
  {
    title: "Destiny Recipes",
    href: "https://destinyrecipes.com/",
    category: "inventory",
    description: "Vault cleaner, loot companion, checklists, and power progress.",
    tags: ["vault", "loot", "checklist"],
  },
  {
    title: "Mobalytics Builds",
    href: "https://mobalytics.gg/destiny-2/builds",
    category: "builds",
    description: "Builds and guide pages by class and activity.",
    tags: ["builds", "guides", "classes"],
  },
  {
    title: "Mobalytics Build Planner",
    href: "https://mobalytics.gg/destiny-2/build-planner",
    category: "builds",
    description: "Build planner with abilities, armor, weapons, and DIM links.",
    tags: ["planner", "sharing", "loadouts"],
  },
  {
    title: "light.gg",
    href: "https://www.light.gg/",
    category: "weapons",
    description: "Item database for weapons, rolls, collections, triumphs, and catalysts.",
    tags: ["database", "rolls", "items"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "light.gg Monument Weapons",
    href: "https://www.light.gg/db/new-items/monument-of-triumph/new-weapons/",
    category: "weapons",
    description: "New and reprised Monument of Triumph weapons.",
    tags: ["monument", "weapons", "new items"],
    monumentRelevant: true,
  },
  {
    title: "light.gg New Catalysts",
    href: "https://www.light.gg/db/new-items/monument-of-triumph/new-catalysts/",
    category: "weapons",
    description: "Monument of Triumph Exotic catalyst list.",
    tags: ["monument", "catalysts", "exotics"],
    monumentRelevant: true,
  },
  {
    title: "D2 Foundry",
    href: "https://d2foundry.gg/",
    category: "weapons",
    description: "Weapon roll explorer and perk calculator.",
    tags: ["rolls", "perks", "crafting"],
    featured: true,
  },
  {
    title: "D2 Arsenal",
    href: "https://www.d2arsenal.com/",
    category: "weapons",
    description: "Roll crafting and weapon sharing.",
    tags: ["rolls", "weapons", "sharing"],
  },
  {
    title: "Destiny Report",
    href: "https://destiny.report/",
    iconUrl: "https://destiny.report/a/3044c57c.png",
    category: "weapons",
    description: "Weapon search by perk, frame, damage type, ammo, and source.",
    tags: ["weapon search", "perks", "sources"],
  },
  {
    title: "TodayInDestiny",
    href: "https://www.todayindestiny.com/",
    category: "activities",
    description: "Activities, vendors, lost sectors, and rotations.",
    tags: ["rotations", "vendors", "calendar"],
    featured: true,
  },
  {
    title: "Braytech",
    href: "https://bray.tech/",
    category: "activities",
    description: "Maps, checklists, triumphs, collections, and weeklies.",
    tags: ["maps", "triumphs", "collections"],
  },
  {
    title: "Ishtar Collective",
    href: "https://www.ishtar-collective.net/",
    category: "reference",
    description: "Lore archive, releases, books, transcripts, and item text.",
    tags: ["lore", "archive", "releases"],
    monumentRelevant: true,
  },
  {
    title: "Kyber's Corner",
    href: "https://kyberscorner.com/destiny2/",
    category: "reference",
    description: "Weekly reset, Xur, Trials, activity guides, and infographics.",
    tags: ["guides", "weekly reset", "infographics"],
    monumentRelevant: true,
  },
  {
    title: "Raid Report",
    href: "https://raid.report/",
    category: "activities",
    description: "Raid clears, speedruns, sherpas, leaderboards, and weekly progress.",
    tags: ["raids", "leaderboards", "sherpas"],
    featured: true,
    monumentRelevant: true,
  },
  {
    title: "Dungeon Report",
    href: "https://dungeon.report/",
    category: "activities",
    description: "Dungeon clears, speedruns, sherpas, leaderboards, and weekly progress.",
    tags: ["dungeons", "leaderboards", "sherpas"],
    monumentRelevant: true,
  },
  {
    title: "D2Checkpoint",
    href: "https://d2checkpoint.com/",
    category: "activities",
    description: "Raid and dungeon checkpoint bot status and access links.",
    tags: ["checkpoints", "raids", "dungeons"],
  },
  {
    title: "activities.report",
    href: "https://activities.report/",
    category: "activities",
    description: "Activity history and post-game stats.",
    tags: ["activity history", "stats", "pgcr"],
  },
  {
    title: "Destiny Tracker",
    href: "https://destinytracker.com/",
    category: "stats",
    description: "Profile stats, PvP meta, leaderboards, match history, and rankings.",
    tags: ["stats", "leaderboards", "pvp"],
  },
  {
    title: "Trials Report",
    href: "https://destinytrialsreport.com/",
    category: "stats",
    description: "Trials opponents, teammates, loadouts, and weekly runs.",
    tags: ["trials", "pvp", "opponents"],
  },
  {
    title: "Guardian Report",
    href: "https://guardian.report/",
    category: "stats",
    description: "Opponent, teammate, and profile lookup across modes.",
    tags: ["lookup", "pvp", "profiles"],
  },
  {
    title: "RaidHub",
    href: "https://raidhub.io/",
    category: "stats",
    description: "Raid analytics, profiles, leaderboards, and completion data.",
    tags: ["raids", "analytics", "profiles"],
  },
  {
    title: "Time Wasted on Destiny",
    href: "https://wastedondestiny.com/",
    category: "stats",
    description: "Active playtime, activity breakdowns, titles, and leaderboards.",
    tags: ["playtime", "leaderboards", "profiles"],
  },
  {
    title: "TodayInDestiny Eververse",
    href: "https://www.todayindestiny.com/everversecalendar",
    category: "cosmetics",
    description: "Eververse calendar and Bright Dust planning.",
    tags: ["eververse", "bright dust", "calendar"],
  },
  {
    title: "Bungie Rewards",
    href: "https://bungiestore.com/bungie-rewards",
    category: "cosmetics",
    description: "Bungie Rewards tied to in-game accomplishments.",
    tags: ["rewards", "store", "cosmetics"],
  },
  {
    title: "Bungie Fireteam Finder",
    href: "https://www.bungie.net/7/en/FireteamFinder",
    category: "social",
    description: "Official fireteam listings.",
    tags: ["lfg", "fireteams", "official"],
    monumentRelevant: true,
  },
  {
    title: "loot.report",
    href: "https://loot.report/",
    category: "social",
    description: "Clan raid and dungeon completion tracking.",
    tags: ["clan", "raids", "dungeons"],
  },
  {
    title: "Charlemagne",
    href: "https://warmind.io/",
    category: "social",
    description: "Destiny Discord bot for clans, stats, leaderboards, and automation.",
    tags: ["discord", "clans", "stats"],
  },
];
